package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
BlameLine blame line

swagger:model BlameLine
*/
type BlameLine struct {

	/* Author author
	 */
	Author PersonIdent `json:"author,omitempty"`

	/* CommitID commit id
	 */
	CommitID string `json:"commitId,omitempty"`

	/* Data data
	 */
	Data string `json:"data,omitempty"`

	/* FullMessage full message
	 */
	FullMessage string `json:"fullMessage,omitempty"`

	/* LineNumber line number
	 */
	LineNumber int32 `json:"lineNumber,omitempty"`

	/* ShortMessage short message
	 */
	ShortMessage string `json:"shortMessage,omitempty"`

	/* When when
	 */
	When strfmt.DateTime `json:"when,omitempty"`
}
