package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
CommitDTO commit d t o

swagger:model CommitDTO
*/
type CommitDTO struct {

	/* AllMessage all message
	 */
	AllMessage string `json:"allMessage,omitempty"`

	/* CommitID commit id
	 */
	CommitID string `json:"commitId,omitempty"`

	/* CommitTime commit time
	 */
	CommitTime strfmt.DateTime `json:"commitTime,omitempty"`

	/* Committer committer
	 */
	Committer CommitterDTO `json:"committer,omitempty"`

	/* FullMessage full message
	 */
	FullMessage string `json:"fullMessage,omitempty"`

	/* NotesCount notes count
	 */
	NotesCount int64 `json:"notesCount,omitempty"`

	/* ShortMessage short message
	 */
	ShortMessage string `json:"shortMessage,omitempty"`
}
