package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
CommitterDTO committer d t o

swagger:model CommitterDTO
*/
type CommitterDTO struct {

	/* Avatar avatar
	 */
	Avatar string `json:"avatar,omitempty"`

	/* Email email
	 */
	Email string `json:"email,omitempty"`

	/* Link link
	 */
	Link string `json:"link,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`
}
