package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
DepotDTO depot d t o

swagger:model DepotDTO
*/
type DepotDTO struct {

	/* CreatedAt created at
	 */
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	/* DefaultBranch default branch
	 */
	DefaultBranch string `json:"default_branch,omitempty"`

	/* DepotPath depot path
	 */
	DepotPath string `json:"depot_path,omitempty"`

	/* HasCommits has commits
	 */
	HasCommits bool `json:"hasCommits,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* Language language
	 */
	Language string `json:"language,omitempty"`

	/* Languages languages
	 */
	Languages map[string]interface{} `json:"languages,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* OriginURL origin url
	 */
	OriginURL string `json:"origin_url,omitempty"`

	/* Owner owner
	 */
	Owner UserDTO `json:"owner,omitempty"`

	/* Parent parent
	 */
	Parent *DepotDTO `json:"parent,omitempty"`

	/* ParentID parent id
	 */
	ParentID int32 `json:"parent_id,omitempty"`

	/* Path path
	 */
	Path string `json:"path,omitempty"`

	/* ProjectID project id
	 */
	ProjectID int32 `json:"project_id,omitempty"`

	/* RootID root id
	 */
	RootID int32 `json:"root_id,omitempty"`

	/* Size size
	 */
	Size int64 `json:"size,omitempty"`

	/* Status status
	 */
	Status int32 `json:"status,omitempty"`
}
