package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
DiffStat diff stat

swagger:model DiffStat
*/
type DiffStat struct {

	/* CommitID commit id
	 */
	CommitID string `json:"commitId,omitempty"`

	/* Deletions deletions
	 */
	Deletions int32 `json:"deletions,omitempty"`

	/* Insertions insertions
	 */
	Insertions int32 `json:"insertions,omitempty"`

	/* Paths paths
	 */
	Paths []DiffEntry `json:"paths,omitempty"`
}
