package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
DirDTO dir d t o

swagger:model DirDTO
*/
type DirDTO struct {

	/* CreatedAt created at
	 */
	CreatedAt Timestamp `json:"created_at,omitempty"`

	/* FileID file id
	 */
	FileID int32 `json:"file_id,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* OwnerName owner name
	 */
	OwnerName string `json:"owner_name,omitempty"`

	/* ParentID parent id
	 */
	ParentID int32 `json:"parent_id,omitempty"`

	/* SubFolders sub folders
	 */
	SubFolders []DirDTO `json:"sub_folders,omitempty"`

	/* Type type
	 */
	Type int32 `json:"type,omitempty"`

	/* UpdatedAt updated at
	 */
	UpdatedAt Timestamp `json:"updated_at,omitempty"`
}
