package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
FileDTO file d t o

swagger:model FileDTO
*/
type FileDTO struct {

	/* Comments comments
	 */
	Comments int32 `json:"comments,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt Timestamp `json:"created_at,omitempty"`

	/* CurrentUserRoleID current user role id
	 */
	CurrentUserRoleID int32 `json:"current_user_role_id,omitempty"`

	/* FileType file type
	 */
	FileType string `json:"fileType,omitempty"`

	/* FileID file id
	 */
	FileID int32 `json:"file_id,omitempty"`

	/* HistoryID history id
	 */
	HistoryID int32 `json:"history_id,omitempty"`

	/* ImageInfoURL image info url
	 */
	ImageInfoURL string `json:"image_info_url,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* Number number
	 */
	Number int32 `json:"number,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* OwnerPreview owner preview
	 */
	OwnerPreview string `json:"owner_preview,omitempty"`

	/* ParentID parent id
	 */
	ParentID int32 `json:"parent_id,omitempty"`

	/* Preview preview
	 */
	Preview string `json:"preview,omitempty"`

	/* ShareURL share url
	 */
	ShareURL string `json:"share_url,omitempty"`

	/* Size size
	 */
	Size int64 `json:"size,omitempty"`

	/* StorageKey storage key
	 */
	StorageKey string `json:"storage_key,omitempty"`

	/* StorageType storage type
	 */
	StorageType string `json:"storage_type,omitempty"`

	/* Type type
	 */
	Type int32 `json:"type,omitempty"`

	/* UpdatedAt updated at
	 */
	UpdatedAt Timestamp `json:"updated_at,omitempty"`
}
