package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
FileHistoryDTO file history d t o

swagger:model FileHistoryDTO
*/
type FileHistoryDTO struct {

	/* Action action
	 */
	Action int32 `json:"action,omitempty"`

	/* ActionMsg action msg
	 */
	ActionMsg string `json:"action_msg,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt Timestamp `json:"created_at,omitempty"`

	/* FileType file type
	 */
	FileType string `json:"fileType,omitempty"`

	/* FileID file id
	 */
	FileID int32 `json:"file_id,omitempty"`

	/* HistoryID history id
	 */
	HistoryID int32 `json:"history_id,omitempty"`

	/* ImageHeight image height
	 */
	ImageHeight int32 `json:"image_height,omitempty"`

	/* ImageWidth image width
	 */
	ImageWidth int32 `json:"image_width,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* OwnerPreview owner preview
	 */
	OwnerPreview string `json:"owner_preview,omitempty"`

	/* ParentID parent id
	 */
	ParentID int32 `json:"parent_id,omitempty"`

	/* Preview preview
	 */
	Preview string `json:"preview,omitempty"`

	/* Remark remark
	 */
	Remark string `json:"remark,omitempty"`

	/* Size size
	 */
	Size int32 `json:"size,omitempty"`

	/* StorageKey storage key
	 */
	StorageKey string `json:"storage_key,omitempty"`

	/* StorageType storage type
	 */
	StorageType string `json:"storage_type,omitempty"`

	/* Type type
	 */
	Type int32 `json:"type,omitempty"`

	/* Version version
	 */
	Version int64 `json:"version,omitempty"`
}
