package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
FolderFileCount folder file count

swagger:model FolderFileCount
*/
type FolderFileCount struct {

	/* Count count
	 */
	Count int64 `json:"count,omitempty"`

	/* Folder folder
	 */
	Folder int32 `json:"folder,omitempty"`
}
