package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
KeyDTO key d t o

swagger:model KeyDTO
*/
type KeyDTO struct {

	/* CreatedAt created at
	 */
	CreatedAt Timestamp `json:"created_at,omitempty"`

	/* FingerPrint finger print
	 */
	FingerPrint string `json:"finger_print,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* Title title
	 */
	Title string `json:"title,omitempty"`

	/* Type type
	 */
	Type string `json:"type,omitempty"`
}
