package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
MapOfstringAndstring map ofstring andstring

swagger:model MapOfstringAndstring
*/
type MapOfstringAndstring map[string]string
