package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
MergeRequestDetailDTO merge request detail d t o

swagger:model MergeRequestDetailDTO
*/
type MergeRequestDetailDTO struct {

	/* ActionAt action at
	 */
	ActionAt strfmt.DateTime `json:"action_at,omitempty"`

	/* ActionAuthor action author
	 */
	ActionAuthor UserDTO `json:"action_author,omitempty"`

	/* Author author
	 */
	Author UserDTO `json:"author,omitempty"`

	/* Body body
	 */
	Body string `json:"body,omitempty"`

	/* CommentCount comment count
	 */
	CommentCount int32 `json:"comment_count,omitempty"`

	/* Commits commits
	 */
	Commits []CommitDTO `json:"commits,omitempty"`

	/* Content content
	 */
	Content string `json:"content,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	/* DesBranch des branch
	 */
	DesBranch string `json:"desBranch,omitempty"`

	/* DiffStat diff stat
	 */
	DiffStat DiffStat `json:"diffStat,omitempty"`

	/* Granted granted
	 */
	Granted int32 `json:"granted,omitempty"`

	/* GrantedBy granted by
	 */
	GrantedBy UserDTO `json:"granted_by,omitempty"`

	/* HTMLDiff html diff
	 */
	HTMLDiff string `json:"htmlDiff,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* Iid iid
	 */
	Iid int32 `json:"iid,omitempty"`

	/* MergeStatus merge status
	 */
	MergeStatus string `json:"merge_status,omitempty"`

	/* MergedSha merged sha
	 */
	MergedSha string `json:"merged_sha,omitempty"`

	/* Path path
	 */
	Path string `json:"path,omitempty"`

	/* SrcBranch src branch
	 */
	SrcBranch string `json:"srcBranch,omitempty"`

	/* Title title
	 */
	Title string `json:"title,omitempty"`
}
