package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
MergeRequestDTO merge request d t o

swagger:model MergeRequestDTO
*/
type MergeRequestDTO struct {

	/* ActionAt action at
	 */
	ActionAt strfmt.DateTime `json:"action_at,omitempty"`

	/* ActionAuthor action author
	 */
	ActionAuthor UserDTO `json:"action_author,omitempty"`

	/* Author author
	 */
	Author UserDTO `json:"author,omitempty"`

	/* CommentCount comment count
	 */
	CommentCount int32 `json:"comment_count,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	/* DesBranch des branch
	 */
	DesBranch string `json:"desBranch,omitempty"`

	/* Granted granted
	 */
	Granted int32 `json:"granted,omitempty"`

	/* GrantedBy granted by
	 */
	GrantedBy UserDTO `json:"granted_by,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* Iid iid
	 */
	Iid int32 `json:"iid,omitempty"`

	/* MergeStatus merge status
	 */
	MergeStatus string `json:"merge_status,omitempty"`

	/* Path path
	 */
	Path string `json:"path,omitempty"`

	/* SrcBranch src branch
	 */
	SrcBranch string `json:"srcBranch,omitempty"`

	/* Title title
	 */
	Title string `json:"title,omitempty"`
}
