package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
NormalizedDiffStat normalized diff stat

swagger:model NormalizedDiffStat
*/
type NormalizedDiffStat struct {

	/* Blanks blanks
	 */
	Blanks int32 `json:"blanks,omitempty"`

	/* Deletions deletions
	 */
	Deletions int32 `json:"deletions,omitempty"`

	/* Insertions insertions
	 */
	Insertions int32 `json:"insertions,omitempty"`
}
