package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
Pager pager

swagger:model Pager
*/
type Pager struct {

	/* Offset offset
	 */
	Offset int32 `json:"offset,omitempty"`

	/* Page page
	 */
	Page int32 `json:"page,omitempty"`

	/* PageSize page size
	 */
	PageSize int32 `json:"pageSize,omitempty"`
}
