package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
PersonIdent person ident

swagger:model PersonIdent
*/
type PersonIdent struct {

	/* EmailAddress email address
	 */
	EmailAddress string `json:"emailAddress,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* TimeZone time zone
	 */
	TimeZone TimeZone `json:"timeZone,omitempty"`

	/* TimeZoneOffset time zone offset
	 */
	TimeZoneOffset int32 `json:"timeZoneOffset,omitempty"`

	/* When when
	 */
	When strfmt.DateTime `json:"when,omitempty"`
}
