package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
ProjectLabelDTO project label d t o

swagger:model ProjectLabelDTO
*/
type ProjectLabelDTO struct {

	/* Color color
	 */
	Color string `json:"color,omitempty"`

	/* Count count
	 */
	Count int64 `json:"count,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* Processing processing
	 */
	Processing int64 `json:"processing,omitempty"`

	/* ProjectID project id
	 */
	ProjectID int32 `json:"project_id,omitempty"`

	/* Type type
	 */
	Type int32 `json:"type,omitempty"`
}
