package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
ProjectDTO project d t o

swagger:model ProjectDTO
*/
type ProjectDTO struct {

	/* Auto auto
	 */
	Auto int32 `json:"auto,omitempty"`

	/* BackendProjectPath backend project path
	 */
	BackendProjectPath string `json:"backend_project_path,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	/* CurrentUserRole current user role
	 */
	CurrentUserRole string `json:"current_user_role,omitempty"`

	/* CurrentUserRoleID current user role id
	 */
	CurrentUserRoleID int32 `json:"current_user_role_id,omitempty"`

	/* DeployMemory deploy memory
	 */
	DeployMemory int32 `json:"deploy_memory,omitempty"`

	/* DepotPath depot path
	 */
	DepotPath string `json:"depot_path,omitempty"`

	/* Description description
	 */
	Description string `json:"description,omitempty"`

	/* ExpiredPlan expired plan
	 */
	ExpiredPlan int32 `json:"expired_plan,omitempty"`

	/* ForkCount fork count
	 */
	ForkCount int32 `json:"fork_count,omitempty"`

	/* Forked forked
	 */
	Forked bool `json:"forked,omitempty"`

	/* GitURL git url
	 */
	GitURL string `json:"git_url,omitempty"`

	/* GroupID group id
	 */
	GroupID int32 `json:"groupId,omitempty"`

	/* GroupName group name
	 */
	GroupName string `json:"groupName,omitempty"`

	/* HTTPSURL https url
	 */
	HTTPSURL string `json:"https_url,omitempty"`

	/* Icon icon
	 */
	Icon string `json:"icon,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* IsPublic is public
	 */
	IsPublic bool `json:"is_public,omitempty"`

	/* LastUpdated last updated
	 */
	LastUpdated strfmt.DateTime `json:"last_updated,omitempty"`

	/* MaxMember max member
	 */
	MaxMember int32 `json:"max_member,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* Owner owner
	 */
	Owner UserDTO `json:"owner,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* OwnerUserHome owner user home
	 */
	OwnerUserHome string `json:"owner_user_home,omitempty"`

	/* OwnerUserName owner user name
	 */
	OwnerUserName string `json:"owner_user_name,omitempty"`

	/* OwnerUserPicture owner user picture
	 */
	OwnerUserPicture string `json:"owner_user_picture,omitempty"`

	/* ParentDepotPath parent depot path
	 */
	ParentDepotPath string `json:"parent_depot_path,omitempty"`

	/* Pin pin
	 */
	Pin bool `json:"pin,omitempty"`

	/* Plan plan
	 */
	Plan int32 `json:"plan,omitempty"`

	/* ProjectPath project path
	 */
	ProjectPath string `json:"project_path,omitempty"`

	/* Recommended recommended
	 */
	Recommended int32 `json:"recommended,omitempty"`

	/* RemainDay remain day
	 */
	RemainDay int32 `json:"remain_day,omitempty"`

	/* SSHURL ssh url
	 */
	SSHURL string `json:"ssh_url,omitempty"`

	/* StarCount star count
	 */
	StarCount int32 `json:"star_count,omitempty"`

	/* Stared stared
	 */
	Stared bool `json:"stared,omitempty"`

	/* Status status
	 */
	Status int32 `json:"status,omitempty"`

	/* Type type
	 */
	Type int32 `json:"type,omitempty"`

	/* UnReadActivitiesCount un read activities count
	 */
	UnReadActivitiesCount int32 `json:"un_read_activities_count,omitempty"`

	/* UpdatedAt updated at
	 */
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`

	/* WatchCount watch count
	 */
	WatchCount int32 `json:"watch_count,omitempty"`

	/* Watched watched
	 */
	Watched bool `json:"watched,omitempty"`
}
