package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
TaskCommentDTO task comment d t o

swagger:model TaskCommentDTO
*/
type TaskCommentDTO struct {

	/* Content content
	 */
	Content string `json:"content,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt Timestamp `json:"created_at,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* Owner owner
	 */
	Owner UserDTO `json:"owner,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* TaskID task id
	 */
	TaskID int32 `json:"taskId,omitempty"`
}
