package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
TaskPageDTO task page d t o

swagger:model TaskPageDTO
*/
type TaskPageDTO struct {

	/* Finished finished
	 */
	Finished int64 `json:"finished,omitempty"`

	/* List list
	 */
	List []TaskDTO `json:"list,omitempty"`

	/* Page page
	 */
	Page int32 `json:"page,omitempty"`

	/* PageSize page size
	 */
	PageSize int32 `json:"pageSize,omitempty"`

	/* Processing processing
	 */
	Processing int64 `json:"processing,omitempty"`

	/* TotalPage total page
	 */
	TotalPage int32 `json:"totalPage,omitempty"`

	/* TotalRow total row
	 */
	TotalRow int64 `json:"totalRow,omitempty"`
}
