package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
Timestamp timestamp

swagger:model Timestamp
*/
type Timestamp struct {

	/* Date date
	 */
	Date int32 `json:"date,omitempty"`

	/* Day day
	 */
	Day int32 `json:"day,omitempty"`

	/* Hours hours
	 */
	Hours int32 `json:"hours,omitempty"`

	/* Minutes minutes
	 */
	Minutes int32 `json:"minutes,omitempty"`

	/* Month month
	 */
	Month int32 `json:"month,omitempty"`

	/* Nanos nanos
	 */
	Nanos int32 `json:"nanos,omitempty"`

	/* Seconds seconds
	 */
	Seconds int32 `json:"seconds,omitempty"`

	/* Time time
	 */
	Time int64 `json:"time,omitempty"`

	/* TimezoneOffset timezone offset
	 */
	TimezoneOffset int32 `json:"timezoneOffset,omitempty"`

	/* Year year
	 */
	Year int32 `json:"year,omitempty"`
}
