package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
TimeZone time zone

swagger:model TimeZone
*/
type TimeZone struct {

	/* DisplayName display name
	 */
	DisplayName string `json:"displayName,omitempty"`

	/* RawOffset raw offset
	 */
	RawOffset int32 `json:"rawOffset,omitempty"`
}
