package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
TweetDTO tweet d t o

swagger:model TweetDTO
*/
type TweetDTO struct {

	/* ActivityID activity id
	 */
	ActivityID int32 `json:"activity_id,omitempty"`

	/* Address address
	 */
	Address string `json:"address,omitempty"`

	/* CommentList comment list
	 */
	CommentList []TweetCommentDTO `json:"comment_list,omitempty"`

	/* Comments comments
	 */
	Comments int32 `json:"comments,omitempty"`

	/* Content content
	 */
	Content string `json:"content,omitempty"`

	/* Coord coord
	 */
	Coord string `json:"coord,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt int64 `json:"created_at,omitempty"` //Timestamp `json:"created_at,omitempty"`

	/* Device device
	 */
	Device string `json:"device,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* LikeUsers like users
	 */
//	LikeUsers []MapOfstringAndstring `json:"like_users,omitempty"`
	LikeUsers []LikeUserDTO `json:"like_users,omitempty"`

	/* Liked liked
	 */
	Liked bool `json:"liked,omitempty"`

	/* Likes likes
	 */
	Likes int32 `json:"likes,omitempty"`

	/* Location location
	 */
	Location string `json:"location,omitempty"`

	/* Owner owner
	 */
	Owner UserDTO `json:"owner,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* Path path
	 */
	Path string `json:"path,omitempty"`
}
