package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
TweetCommentDTO tweet comment d t o

swagger:model TweetCommentDTO
*/
type TweetCommentDTO struct {

	/* Content content
	 */
	Content string `json:"content,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt int64 `json:"created_at,omitempty"` //Timestamp `json:"created_at,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* Owner owner
	 */
	Owner UserDTO `json:"owner,omitempty"`

	/* OwnerID owner id
	 */
	OwnerID int32 `json:"owner_id,omitempty"`

	/* TweetID tweet id
	 */
	TweetID int32 `json:"tweet_id,omitempty"`
}
