package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
TweetLike tweet like

swagger:model TweetLike
*/
type TweetLike struct {

	/* CreatedAt created at
	 */
	CreatedAt Timestamp `json:"created_at,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* TweetID tweet id
	 */
	TweetID int32 `json:"tweet_id,omitempty"`

	/* UserID user id
	 */
	UserID int32 `json:"user_id,omitempty"`
}
