package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
UserFollowDTO user follow d t o

swagger:model UserFollowDTO
*/
type UserFollowDTO struct {

	/* Relation relation
	 */
	Relation int32 `json:"relation,omitempty"`

	/* TargetUserID target user id
	 */
	TargetUserID int32 `json:"target_user_id,omitempty"`

	/* UserID user id
	 */
	UserID int32 `json:"user_id,omitempty"`
}
