package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
UserTaskCount user task count

swagger:model UserTaskCount
*/
type UserTaskCount struct {

	/* Done done
	 */
	Done int32 `json:"done,omitempty"`

	/* Processing processing
	 */
	Processing int32 `json:"processing,omitempty"`

	/* User user
	 */
	User int32 `json:"user,omitempty"`
}
