package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
UserSettingGroupDTO user setting group d t o

swagger:model UserSettingGroupDTO
*/
type UserSettingGroupDTO struct {

	/* EmailKey email key
	 */
	EmailKey string `json:"email_key,omitempty"`

	/* EmailValue email value
	 */
	EmailValue string `json:"email_value,omitempty"`

	/* Flag flag
	 */
	Flag int32 `json:"flag,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* NotificationKey notification key
	 */
	NotificationKey string `json:"notification_key,omitempty"`

	/* NotificationValue notification value
	 */
	NotificationValue string `json:"notification_value,omitempty"`
}
