package models

//import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
UserDTO user d t o

swagger:model UserDTO
*/
type UserDTO struct {

	/* Avatar avatar
	 */
	Avatar string `json:"avatar,omitempty"`

	/* Birthday birthday
	 */
	Birthday string `json:"birthday,omitempty"`

	/* Company company
	 */
	Company string `json:"company,omitempty"`

	/* CreatedAt created at
	 */
	CreatedAt int64 `json:"created_at,omitempty"` //strfmt.DateTime `json:"created_at,omitempty"`

	/* Email email
	 */
	Email string `json:"email,omitempty"`

	/* FansCount fans count
	 */
	FansCount int64 `json:"fans_count,omitempty"`

	/* Follow follow
	 */
	Follow bool `json:"follow,omitempty"`

	/* Followed followed
	 */
	Followed bool `json:"followed,omitempty"`

	/* FollowsCount follows count
	 */
	FollowsCount int64 `json:"follows_count,omitempty"`

	/* GlobalKey global key
	 */
	GlobalKey string `json:"global_key,omitempty"`

	/* Gravatar gravatar
	 */
	Gravatar string `json:"gravatar,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* Introduction introduction
	 */
	Introduction string `json:"introduction,omitempty"`

	/* IsMember is member
	 */
	IsMember int32 `json:"is_member,omitempty"`

	/* IsPhoneValidated is phone validated
	 */
	IsPhoneValidated bool `json:"is_phone_validated,omitempty"`

	/* Job job
	 */
	Job int32 `json:"job,omitempty"`

	/* JobStr job str
	 */
	JobStr string `json:"job_str,omitempty"`

	/* LastActivityAt last activity at
	 */
	LastActivityAt int64 `json:"last_activity_at,omitempty"` //strfmt.DateTime `json:"last_activity_at,omitempty"`

	/* LastLoginedAt last logined at
	 */
	LastLoginedAt int64 `json:"last_logined_at,omitempty"` //strfmt.DateTime `json:"last_logined_at,omitempty"`

	/* Lavatar lavatar
	 */
	Lavatar string `json:"lavatar,omitempty"`

	/* Location location
	 */
	Location string `json:"location,omitempty"`

	/* Name name
	 */
	Name string `json:"name,omitempty"`

	/* NamePinyin name pinyin
	 */
	NamePinyin string `json:"name_pinyin,omitempty"`

	/* Path path
	 */
	Path string `json:"path,omitempty"`

	/* Phone phone
	 */
	Phone string `json:"phone,omitempty"`

	/* Sex sex
	 */
	Sex int32 `json:"sex,omitempty"`

	/* Slogan slogan
	 */
	Slogan string `json:"slogan,omitempty"`

	/* Status status
	 */
	Status int32 `json:"status,omitempty"`

	/* Tags tags
	 */
	Tags string `json:"tags,omitempty"`

	/* TagsStr tags str
	 */
	TagsStr string `json:"tags_str,omitempty"`

	/* Test test
	 */
	Test []string `json:"test,omitempty"`

	/* TweetsCount tweets count
	 */
	TweetsCount int64 `json:"tweets_count,omitempty"`

	/* UpdatedAt updated at
	 */
	UpdatedAt int64 `json:"updated_at,omitempty"` //strfmt.DateTime `json:"updated_at,omitempty"`
}
