package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
UserProjectCount user project count

swagger:model UserProjectCount
*/
type UserProjectCount struct {

	/* Done done
	 */
	Done int32 `json:"done,omitempty"`

	/* Processing processing
	 */
	Processing int32 `json:"processing,omitempty"`

	/* Project project
	 */
	Project int32 `json:"project,omitempty"`
}
