package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
WebHook web hook

swagger:model WebHook
*/
type WebHook struct {

	/* CreatedAt created at
	 */
	CreatedAt Timestamp `json:"created_at,omitempty"`

	/* DepotID depot id
	 */
	DepotID int32 `json:"depot_id,omitempty"`

	/* HookURL hook url
	 */
	HookURL string `json:"hook_url,omitempty"`

	/* ID id
	 */
	ID int32 `json:"id,omitempty"`

	/* SendType send type
	 */
	SendType int32 `json:"send_type,omitempty"`

	/* Status status
	 */
	Status int32 `json:"status,omitempty"`

	/* Token token
	 */
	Token string `json:"token,omitempty"`

	/* Type type
	 */
	Type int32 `json:"type,omitempty"`

	/* UpdatedAt updated at
	 */
	UpdatedAt Timestamp `json:"updated_at,omitempty"`
}
